baseURL = "https://hal.github.io/"
description = "HAL is the project name of the management console used in WildFly and JBoss EAP"
googleAnalytics = "UA-89365654-5"
languageCode = "en-us"
pluralizeListTitles = false
title = "HAL Management Console"
theme = "hal"

[[menu.global]]
  name = "Home"
  weight = 10
  url = "/"
[[menu.global]]
  name = "Documentation"
  weight = 20
  url = "/documentation/"
[[menu.global]]
  name = "Contribute"
  weight = 30
  url = "/contribute/"
[[menu.global]]
  name = "Download"
  weight = 40
  url = "/download/"

[[menu.external]]
  name = "Source Code"
  identifier = "code"
  weight = 10
  post = "fab fa-github"
  url = "https://github.com/hal/hal.next"
[[menu.external]]
  name = "Gitter"
  identifier = "gitter"
  weight = 20
  post = "fab fa-gitter"
  url = "https://gitter.im/hal/hal.next"
[[menu.external]]
  name = "Issues"
  identifier = "issues"
  weight = 30
  post = "fas fa-bug"
  url = "https://issues.jboss.org/projects/HAL/issues"

[[menu.footer]]
  name = "Related"
  identifier = "related"
  weight = 10
[[menu.footer]]
  name = "WildFly"
  parent = "related"
  weight = 100
  url = "http://wildfly.org/"
[[menu.footer]]
  name = "GWT"
  parent = "related"
  weight = 110
  url = "http://www.gwtproject.org/"
[[menu.footer]]
  name = "Elemento"
  parent = "related"
  weight = 120
  url = "https://github.com/hal/elemento"
[[menu.footer]]
  name = "Documentation"
  identifier = "documentation"
  weight = 20
[[menu.footer]]
  name = "Get started"
  parent = "documentation"
  weight = 200
  url = "/documentation/get-started/"
[[menu.footer]]
  name = "End User"
  parent = "documentation"
  weight = 210
  url = "/documentation/end-user"
[[menu.footer]]
  name = "Developer"
  parent = "documentation"
  weight = 220
  url = "/documentation/developer"
[[menu.footer]]
  name = "Contribute"
  identifier = "contribute"
  weight = 30
[[menu.footer]]
  name = "Submit a Bug"
  parent = "contribute"
  weight = 300
  url = "https://issues.jboss.org/projects/HAL/issues"
[[menu.footer]]
  name = "Fork the Code"
  parent = "contribute"
  weight = 310
  url = "https://github.com/hal/hal.next/fork"
[[menu.footer]]
  name = "Build & Run"
  parent = "contribute"
  weight = 320
  url = "/build/"

[taxonomies]
  tag = "tags"
  category = "categories"
