baseURL = "https://hal.github.io/"
description = "HAL is the project name of the management console used in WildFly and JBoss EAP"
googleAnalytics = "UA-89365654-5"
languageCode = "en-us"
title = "HAL Management Console"
theme = "kube"

[Params]
  author = "Harald Pehl" 
  github = "hpehl" 
  twitter = "@haraldpehl"

[[menu.main]]
    name = "About"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
