baseURL = "https://hal.github.io/"
description = "HAL is the project name of the management console used in WildFly and JBoss EAP"
googleAnalytics = "UA-89365654-5"
languageCode = "en-us"
title = "HAL Management Console"
theme = "hal"

[[menu.global]]
  name = "About"
  weight = 10
  url = "/about/"
[[menu.global]]
  name = "Documentation"
  weight = 20
  url = "/documentation/"
[[menu.global]]
  name = "Community"
  weight = 30
  url = "/community/"
[[menu.global]]
  name = "Download"
  weight = 40
  url = "/download/"

[[menu.external]]
    name = "Source Code"
    identifier = "code"
    weight = 10
    post = "fab fa-github"
    url = "https://github.com/hal/hal.next"
[[menu.external]]
    name = "Gitter"
    identifier = "gitter"
    weight = 20
    post = "fab fa-gitter"
    url = "https://gitter.im/hal/hal.next"
[[menu.external]]
    name = "Issues"
    identifier = "issues"
    weight = 30
    post = "fas fa-bug"
    url = "https://issues.jboss.org/projects/HAL/issues"

[taxonomies]
  tag = "tags"
  category = "categories"
